### ISSUE TITLE
Uncaught Error: Cannot find module || Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by Curstantine** [pablo-abc/svelte-markdown#19]
`Uncaught Error: Cannot find module '~~/node_modules/svelte-markdown/dist/sveltemarkdown.js'. Please verify that the package.json has a valid "main" entry` gets returned when used like this:
```js
<script>
  import SvelteMarkdown from "svelte-markdown";
  export let value =
</script>
//...
 <article>
    <SvelteMarkdown {value} />
 </article>
```

```js
// package.json
  "dependencies": {
// ...
    "svelte-markdown": "^0.1.10",
  },
```
![image](https://user-images.githubusercontent.com/69104500/123595201-42fdc080-d80e-11eb-8177-d934bbcee794.png)

**Comment by quasarchimaere** [comment]
i am currently running into the same issue, did you fix this by adding it to the devDependencies?

**Comment by Curstantine** [comment]
Tried both, I thought I was doing something wrong so I closed the issue.

**Comment by quasarchimaere** [comment]
Ok just as a generic Info, as described in the readme you have to add `svelte-markdown` as a devDependency if you use sapper, but only as a devDependency, our issue was that we did not remove the normal dependency and thus fell into the same issue as described above, it works for us now

**Comment by pablo-abc** [comment]
Should I be more specific about Sapper usage in the README? Since people seem to be jumping to SvelteKit I didn't worry too much aboutt that.

 One thing I noticed from your snippet, @Curstantine  is that the prop for Svelte Markdown should be called `source` not `value`. So `<SvelteMarkdown source={value} />` should work.

**Comment by quasarchimaere** [comment]
@pablo-abc i don't know if being more specific about sapper would help, afaik it seems to work just fine if you are able to read and do things according to your description. maybe you should make a distinction between sveltekit and sapper, since sveltekit is by far not production ready yet
