### ISSUE TITLE
editable?

### ISSUE THREAD

**Issue by zahachtah** [pablo-abc/svelte-markdown#20]
Hi, I tried to make the source editable and got an error. This could be my bad javascript knowledge but this is how I have done before. without the bind this repl with not error but then the edited text does not bind to the source variable. Any ideas how to solve? or even make it part of the component?

https://svelte.dev/repl/6b8e40cb230b4c46a4db35377407a20d?version=3.38.3

Thanks

**Comment by zahachtah** [comment]
me stupid, I just need to declare source with let instead of const. Sorry...

**Comment by pablo-abc** [comment]
Yep! Haha, just adding that I don't think it is possible to do this binding to `source`, since it passes through `marked`, as far as I know it'd be impossible to keep it reactive all the way down to the nodes that render the markdown.
