### ISSUE TITLE
code formatting

### ISSUE THREAD

**Issue by magick93** [pablo-abc/svelte-markdown#24]
Is there anything additional I need to do to get code formating to work?

The markdown I'm using is (the \ only to the below so the code can be rendered in GH):

```
\```
const getAdapters = (adapt) => {
    // eslint-disable-next-line no-console
    console.log(`adapter is ${adapt}`);
    switch (adapt) {
        case 'node':
            return nodeAdapter;
        case 'static':
            return staticAdapter;
        case 'netlify':
            return netlifyAdapter;
        case 'vercel':
            return vercelAdapter;
        default:
            return nodeAdapter;
    }
};
\```
```

When rendered, the output is exactly as the input.

Thanks

**Comment by pablo-abc** [comment]
I'm closing this since there was no further follow ups. If this still does not work for you somehow, feel free to reopen it.
