### ISSUE TITLE
Link from npm to github

### ISSUE THREAD

**Issue by retani** [pablo-abc/svelte-markdown#4]
Thanks a lot for this package 🙏
Would you be so kind as to add a link from the npm page (top result when searching "svelte markdown") to this github repository page? It's actually quite hard to find the code without it. Thanks.

![image](https://user-images.githubusercontent.com/3465427/108621853-81850800-7435-11eb-866e-4527b90b6fe6.png)

**Comment by pablo-abc** [comment]
Oops! Can't believe I had not noticed that. Thanks for the heads up!

**Comment by pablo-abc** [comment]
Should be linked now! Had to increase a patch version to post it on npm, no changes to the code itself between 0.1.2 and 0.1.3.
