### ISSUE TITLE
Using anchor links in markdown.

### ISSUE THREAD

**Issue by fejiroofficial** [pablo-abc/svelte-markdown#40]
I have an anchor link in the markdown. But it returns an empty one in the end.
Markdown: `<a href="/privacy" title="Privacy and Cookie Policy">Privacy and Cookie Policy</a>`

Outcome: `<a href="/privacy" title="Privacy and Cookie Policy"></a>Privacy and Cookie Policy`

What am I missing?

**Comment by pablo-abc** [comment]
This is a known issue. Due to how Svelte's `{@html }`, it's not possible to have a mix of both HTML tags and markdown in the same paragraph. If you want to use HTML, the paragraph should use _only_ HTML (and you should wrap it between `<p>`).

**Comment by fejiroofficial** [comment]
Oh alright thanks

**Comment by pablo-abc** [comment]
Closing this since I added [a note to the README](https://github.com/pablo-abc/svelte-markdown#html-rendering).
