### ISSUE TITLE
Error when using svelte-markdown in sveltekit

### ISSUE THREAD

**Issue by asv1** [pablo-abc/svelte-markdown#7]
Such error i got:

```
Cannot read property 'Lexer' of undefined
```

It installed as usual dependency. If i instal it as devdependency it cannot be found.

**Comment by asv1** [comment]
Looks like something with sveltekit.

**Comment by emme1444** [comment]
Hey @asv1! Did you ever get around this? I'm getting the same error.

**Comment by asv1** [comment]
@emme1444 
You need replace in file ```markdown-parser.js``` from ```import marked from 'marked'``` to ```import marked from 'marked/lib/marked.esm.js'```. It because sveltekit wants esm module to import.

**Comment by pablo-abc** [comment]
@asv1 I had been scratching my head on how to solve it while not breaking other environments. Have you tested if changing the import would not break it for plain Svelte with Rollup or Sapper? If so I can make the change as a patch here.

**Comment by asv1** [comment]
@pablo-abc 
Rollup can import esm? So is sapper to, i am right?

**Comment by emme1444** [comment]
@asv1 Thanks for the quick response! I went a different route by using [MDsveX](https://mdsvex.pngwn.io/) instead. But good luck!

**Comment by tomekrozalski** [comment]
@pablo-abc it was closed, but issue still occurs when I try it with SvelteKit :(

**Comment by pablo-abc** [comment]
@tomekrozalski which version of this package are you using? I'm currently using this with SvelteKit [here without any issues](https://github.com/pablo-abc/felte/blob/main/packages/site/package.json).
Are you getting the same error as the original issue?
